name: Sync to Parent Folder

on:
  push:
    branches:
      - main  # Or whichever branch you want to monitor

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout child repo
        uses: actions/checkout@v4

      - name: Set up Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Clone parent repo
        run: |
          git clone https://x-access-token:${{ secrets.PARENT_REPO_PAT }}@github.com/laksrith/prompt_parent.git parent
          cd parent
          git checkout main

      - name: Copy specific files and folders to parent repo
        run: |
          mkdir -p parent/prompt_child

          # Copy all .py, .ipynb, .md files recursively from child repo
          find . -type f \( -name "*.py" -o -name "*.ipynb" -o -name "*.md" \) -exec cp --parents {} parent/prompt_child/ \;

          # Copy specific folders (adjust as needed)
          cp -r data parent/prompt_child/
          cp -r models parent/prompt_child/

      - name: Commit & Push to Parent Repo
        run: |
          cd parent
          git add prompt_child
          git commit -m "Sync from child repo: ${{ github.sha }}" || echo "No changes to commit"
          git push origin main
